# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target basis.utilities_cxx
ADD_LIBRARY(basis.utilities_cxx STATIC IMPORTED)

# Create imported target basis.basis
ADD_LIBRARY(basis.basis STATIC IMPORTED)

# Create imported target basis.testlib
ADD_LIBRARY(basis.testlib STATIC IMPORTED)

# Create imported target basis.testmain
ADD_LIBRARY(basis.testmain STATIC IMPORTED)

# Create imported target basis.testdriver
ADD_EXECUTABLE(basis.testdriver IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/BASISExports-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
