# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target dramms.basis
ADD_LIBRARY(dramms.basis STATIC IMPORTED)

# Create imported target dramms.common
ADD_LIBRARY(dramms.common STATIC IMPORTED)

# Create imported target dramms.CheckTwoImages
ADD_EXECUTABLE(dramms.CheckTwoImages IMPORTED)

# Create imported target dramms.GenerateGaborListFile
ADD_EXECUTABLE(dramms.GenerateGaborListFile IMPORTED)

# Create imported target dramms.GenerateImageListFile
ADD_EXECUTABLE(dramms.GenerateImageListFile IMPORTED)

# Create imported target dramms.CalculateImageSimilarity
ADD_EXECUTABLE(dramms.CalculateImageSimilarity IMPORTED)

# Create imported target dramms.CombineFeatureLists
ADD_EXECUTABLE(dramms.CombineFeatureLists IMPORTED)

# Create imported target dramms.CombineTransforms
ADD_EXECUTABLE(dramms.CombineTransforms IMPORTED)

# Create imported target dramms.CalculateGaborTextures
ADD_EXECUTABLE(dramms.CalculateGaborTextures IMPORTED)

# Create imported target dramms.MatchHistograms
ADD_EXECUTABLE(dramms.MatchHistograms IMPORTED)

# Create imported target dramms.ApplyTransform
ADD_EXECUTABLE(dramms.ApplyTransform IMPORTED)

# Create imported target dramms.CalculateJacobianMap
ADD_EXECUTABLE(dramms.CalculateJacobianMap IMPORTED)

# Create imported target dramms.CalculateRavensMaps
ADD_EXECUTABLE(dramms.CalculateRavensMaps IMPORTED)

# Create imported target dramms.ImageOperation
ADD_EXECUTABLE(dramms.ImageOperation IMPORTED)

# Create imported target dramms.TransformOperation
ADD_EXECUTABLE(dramms.TransformOperation IMPORTED)

# Create imported target dramms.ConvertDeformation
ADD_EXECUTABLE(dramms.ConvertDeformation IMPORTED)

# Create imported target dramms.ConvertImage
ADD_EXECUTABLE(dramms.ConvertImage IMPORTED)

# Create imported target dramms.Deform2D
ADD_EXECUTABLE(dramms.Deform2D IMPORTED)

# Create imported target dramms.Deform3D
ADD_EXECUTABLE(dramms.Deform3D IMPORTED)

# Load information for each installed configuration.
GET_FILENAME_COMPONENT(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
FILE(GLOB CONFIG_FILES "${_DIR}/DRAMMSExports-*.cmake")
FOREACH(f ${CONFIG_FILES})
  INCLUDE(${f})
ENDFOREACH(f)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
