# Generated by CMake 3.0.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget dramms.basis dramms.common dramms.CheckTwoImages dramms.GenerateGaborListFile dramms.GenerateImageListFile dramms.CalculateImageSimilarity dramms.CombineFeatureLists dramms.CombineTransforms dramms.CalculateGaborTextures dramms.MatchHistograms dramms.ApplyTransform dramms.CalculateJacobianMap dramms.CalculateRavensMaps dramms.ImageOperation dramms.TransformOperation dramms.ConvertDeformation dramms.ConvertImage dramms.Deform2D dramms.Deform3D)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target dramms.basis
add_library(dramms.basis STATIC IMPORTED)

# Create imported target dramms.common
add_library(dramms.common STATIC IMPORTED)

# Create imported target dramms.CheckTwoImages
add_executable(dramms.CheckTwoImages IMPORTED)

# Create imported target dramms.GenerateGaborListFile
add_executable(dramms.GenerateGaborListFile IMPORTED)

# Create imported target dramms.GenerateImageListFile
add_executable(dramms.GenerateImageListFile IMPORTED)

# Create imported target dramms.CalculateImageSimilarity
add_executable(dramms.CalculateImageSimilarity IMPORTED)

# Create imported target dramms.CombineFeatureLists
add_executable(dramms.CombineFeatureLists IMPORTED)

# Create imported target dramms.CombineTransforms
add_executable(dramms.CombineTransforms IMPORTED)

# Create imported target dramms.CalculateGaborTextures
add_executable(dramms.CalculateGaborTextures IMPORTED)

# Create imported target dramms.MatchHistograms
add_executable(dramms.MatchHistograms IMPORTED)

# Create imported target dramms.ApplyTransform
add_executable(dramms.ApplyTransform IMPORTED)

# Create imported target dramms.CalculateJacobianMap
add_executable(dramms.CalculateJacobianMap IMPORTED)

# Create imported target dramms.CalculateRavensMaps
add_executable(dramms.CalculateRavensMaps IMPORTED)

# Create imported target dramms.ImageOperation
add_executable(dramms.ImageOperation IMPORTED)

# Create imported target dramms.TransformOperation
add_executable(dramms.TransformOperation IMPORTED)

# Create imported target dramms.ConvertDeformation
add_executable(dramms.ConvertDeformation IMPORTED)

# Create imported target dramms.ConvertImage
add_executable(dramms.ConvertImage IMPORTED)

# Create imported target dramms.Deform2D
add_executable(dramms.Deform2D IMPORTED)

# Create imported target dramms.Deform3D
add_executable(dramms.Deform3D IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/DRAMMSExports-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
